In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import pylab as plt

df = pd.read_excel('AirQualityUCI.xlsx')

def is_real_and_finite(x):
    if not np.isreal(x):
        return False
    elif not np.isfinite(x):
        return False
    else:
        return True
    
all_data = df[df.columns[0:]].values

print(all_data)
#numeric_map = df[df.columns[1:]].applymap(is_real_and_finite)
#real_rows = numeric_map.all(axis = 1).copy().values
X = np.array(all_data[:, 1:])
y = np.array(all_data[:, -2]) #what are we looking for???
y = y.reshape(-1, 1)

[[Timestamp('2004-11-23 00:00:00') datetime.time(19, 0) 11.9 ... 74.7
  1.0741 'Very High']
 [Timestamp('2004-11-23 00:00:00') datetime.time(20, 0) 11.5 ... 76.2
  1.0324 'Very High']
 [Timestamp('2004-11-17 00:00:00') datetime.time(18, 0) 10.2 ... 52.8
  0.8244 'Very High']
 ...
 [Timestamp('2005-03-29 00:00:00') datetime.time(4, 0) -200.0 ... 68.2
  1.0611 'Very low']
 [Timestamp('2005-04-01 00:00:00') datetime.time(4, 0) -200.0 ... 48.8
  0.7606 'Very low']
 [Timestamp('2005-04-04 00:00:00') datetime.time(4, 0) -200.0 ... 56.0
  0.7743 'Very low']]


In [2]:
data = []
data = np.array([df['CO_GT'].values,df['PT08_S1_CO'].values,df['NMHC_GT'].values,df['C6H6_GT'].values,df['PT08_S2_NMHC'].values,df['Nox_GT'].values,df['PT08_S3_Nox'].values,df['NO2_GT'].values,df['PT08_S4_NO2'].values,df['PT08_S5_O3'].values,df['T'].values,df['RH'].values,df['AH'].values,df['CO_level'].values])
#print(data) #all data where each row is a feature
print(np.shape(data))
#transpose so it looks like Excel sheet where columns are features
X = data.T
print(X)

(14, 9357)
[[11.9 2008 -200 ... 74.7 1.0741 'Very High']
 [11.5 1918 -200 ... 76.2 1.0324 'Very High']
 [10.2 1802 -200 ... 52.8 0.8244 'Very High']
 ...
 [-200.0 883 -200 ... 68.2 1.0611 'Very low']
 [-200.0 818 -200 ... 48.8 0.7606 'Very low']
 [-200.0 864 -200 ... 56.0 0.7743 'Very low']]


In [3]:
#delete last column
X = X[:,0:-1]
print(X)

[[11.9 2008 -200 ... 12.4 74.7 1.0741]
 [11.5 1918 -200 ... 11.5 76.2 1.0324]
 [10.2 1802 -200 ... 13.7 52.8 0.8244]
 ...
 [-200.0 883 -200 ... 13.7 68.2 1.0611]
 [-200.0 818 -200 ... 13.7 48.8 0.7606]
 [-200.0 864 -200 ... 11.8 56.0 0.7743]]


In [4]:
#delete rows where -200 is in one of the columns
ind = []
[r,c] = np.shape(X)
for i in range(r): #loop through rows
    if any(X[i,:] == -200):
        ind = np.append(ind,i) #vector with indices for rows with -200
print(np.shape(ind))
X = np.delete(X, ind, axis = 0)
print(np.shape(X))

#dropping may mess up indices?

(8530,)
(827, 13)


<ipython-input-4-1596676983c5>:8: DeprecationWarning: using a non-integer array as obj in delete will result in an error in the future
  X = np.delete(X, ind, axis = 0)
